export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx}'],
  theme: {
    extend: {
      colors: {
        'background': '#131315',
        'on-background': '#e5e1e4',
        'surface': '#131315',
        'surface-dim': '#131315',
        'surface-bright': '#39393b',
        'surface-container': '#201f21',
        'surface-container-low': '#1b1b1d',
        'surface-container-lowest': '#0e0e10',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#353437',
        'surface-variant': '#353437',
        'on-surface': '#e5e1e4',
        'on-surface-variant': '#d4c4af',
        'inverse-surface': '#e5e1e4',
        'inverse-on-surface': '#313032',
        'inverse-primary': '#7d5800',
        'primary': '#ffd99a',
        'primary-container': '#f5b841',
        'on-primary': '#422c00',
        'on-primary-container': '#6a4a00',
        'primary-fixed': '#ffdea9',
        'primary-fixed-dim': '#fabc45',
        'secondary': '#4edea3',
        'secondary-container': '#00a572',
        'on-secondary': '#003824',
        'on-secondary-container': '#00311f',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'tertiary': '#5cfb88',
        'tertiary-container': '#37de6f',
        'on-tertiary': '#003915',
        'on-tertiary-container': '#005d27',
        'tertiary-fixed': '#66ff8e',
        'tertiary-fixed-dim': '#3de273',
        'on-tertiary-fixed': '#002109',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#9c8f7b',
        'outline-variant': '#504535',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'base': '8px',
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '20px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'vazirmatn': ['Vazirmatn', 'sans-serif'],
      },
    },
  },
};